### PR TITLE
adds formatAbbreviation to axis

### LINKED ISSUE #61: use formatAbbreviate as the default tick formatter
### Expected Behavior
Scales that are not logarithmic and not time should use the new `formatAbbreviate` function from `d3plus-format`. The current logic is here: https://github.com/d3plus/d3plus-axis/blob/master/src/Axis.js#L298-L308

### Current Behavior
Currently, numbers return as is.

### PR DESCRIPTION
**Pull request by cnavarreteliz**
(closes #61)

### Description

- add `format` option. If `format: true`, adds `formatAbbreviate` for every tick in axis.

### Checklist
- [x] I have documented all new methods.
- [ ] I have written tests for all new methods/functionality.
- [x] I have written examples for all new methods/functionality.

### CODE REVIEW

**Comment by cnavarreteliz** [comment]
@davelandry I want to update this PR, because when we used `log` scale in the VizBuilder, the ticks are always represented with exponential values, like 10<sup>8</sup>.

**Comment by cnavarreteliz** [comment]
Yep, You're right :), but we need to merge this PR for to use `formatAbbreviation`

**Comment by davelandry** [comment]
So what is the use of adding a `format` method?

**Comment by davelandry** [comment]
Also, please resolve the conflicts with package.json (pull from master)

**Pull request closed without merging**
